source "https://supermarket.chef.io"



metadata

cookbook 'TFS', path: '../TFS'
cookbook 'ActiveDirectory', path: '../ActiveDirectory'
cookbook 'SQL2014', path: '../SQL2014'
cookbook 'DotNet35', path: '../DotNet35'
cookbook 'Resharper', path: '../Resharper'
cookbook 'AWS4VisualStudio', path: '../AWS4VisualStudio'
cookbook 'iis'
cookbook 's3_file'
