source "https://supermarket.chef.io"

metadata

cookbook 'ec2helper', path: '../ec2helper'
cookbook 'vs', path: '../vs'
cookbook 'PsTools', path: '../PsTools'
cookbook 's3_file'
cookbook 'windows'
cookbook 'iis'