name             'tfs'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures SQL2014'
long_description 'Installs/Configures SQL2014'
version          '0.1.0'

depends 'vs'
depends 'ec2helper'
depends 'PsTools'
depends 's3_file'
depends 'windows'
depends 'iis'